const $=id=>document.getElementById(id),view=$('view'),ctx=view.getContext('2d'),video=$('video'),input=document.createElement('canvas'),ic=input.getContext('2d',{willReadFrequently:true}),map=$('map'),mc=map.getContext('2d');
let worker=new Worker('worker.js'),ready=false,running=false,busy=false,stream=null,mode='',generation=0,frameHandle=0,lastFrame=0,lastMedia=-1,lastResult=0,frameCount=0,demoFrame=0,path=[[0,0,0]],world=VOGeometry.I(),position=[0,0,0],keyframes=0;
const scene=[];let rng=12345;function random(){rng=(1664525*rng+1013904223)>>>0;return rng/4294967296;}for(let i=0;i<650;i++)scene.push([(random()-.5)*18,(random()-.5)*12,4+random()*16,100+random()*155]);
function drawMap(){const w=map.width,h=map.height;mc.fillStyle='#131e28';mc.fillRect(0,0,w,h);mc.strokeStyle='#24333f';mc.lineWidth=1;for(let x=0;x<w;x+=30){mc.beginPath();mc.moveTo(x,0);mc.lineTo(x,h);mc.stroke();}for(let y=0;y<h;y+=30){mc.beginPath();mc.moveTo(0,y);mc.lineTo(w,y);mc.stroke();}let extent=Math.max(5,...path.map(p=>Math.max(Math.abs(p[0]),Math.abs(p[2])))),s=Math.min(w,h)*.4/extent;const xy=p=>[w/2+p[0]*s,h/2-p[2]*s];mc.strokeStyle='#8df3c3';mc.lineWidth=2.5;mc.beginPath();path.forEach((p,i)=>{let [x,y]=xy(p);i?mc.lineTo(x,y):mc.moveTo(x,y);});mc.stroke();let [x,y]=xy(position);mc.fillStyle='#8df3c3';mc.beginPath();mc.arc(x,y,5,0,7);mc.fill();mc.fillStyle='#93aab8';mc.font='12px sans-serif';mc.fillText('X →',w-45,h-16);mc.fillText('Z ↑',14,22);mc.fillText(keyframes+' accepted steps',14,h-16);}
let epoch=0;
function reset(){epoch++;worker.postMessage({type:'reset'});path=[[0,0,0]];world=VOGeometry.I();position=[0,0,0];keyframes=0;drawMap();$('inliers').textContent='—';}
function stop(){generation++;running=false;cancelAnimationFrame(frameHandle);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.pause();video.srcObject=null;$('stop').disabled=true;$('camera').disabled=!ready;$('demo').disabled=!ready;$('mode').textContent='중지';lastMedia=-1;window.removeEventListener('devicemotion',onMotion);clearInterval(imuTimer);imuTimer=null;$('imu').disabled=false;$('imuState').textContent='연결 전';$('imuHz').textContent='— Hz';for(let id of ['fps','features','ms'])$(id).textContent='—';reset();}
function prepare(name){reset();mode=name;running=true;lastFrame=lastResult=0;demoFrame=frameCount=0;$('empty').style.display='none';$('stop').disabled=false;$('camera').disabled=true;$('demo').disabled=true;$('mode').textContent=name==='demo'?'합성 영상':'카메라';}
async function startCamera(){stop();let token=generation;$('camera').disabled=true;$('status').textContent='카메라 권한 확인 중…';try{if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('카메라는 HTTPS 또는 localhost에서 열어야 합니다.');const candidate=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:30}}});if(token!==generation){candidate.getTracks().forEach(t=>t.stop());return;}stream=candidate;video.srcObject=stream;await video.play();if(token!==generation)return;let ratio=video.videoHeight/video.videoWidth;input.width=view.width=384;input.height=view.height=Math.round(384*ratio);view.parentElement.style.aspectRatio=`384 / ${input.height}`;prepare('camera');$('status').textContent='시작했습니다. 제자리 회전보다 옆으로 천천히 이동해 보세요.';frameHandle=requestAnimationFrame(loop);}catch(e){if(token===generation){stop();$('status').textContent=e.name==='NotAllowedError'?'카메라 권한이 거절되었습니다. 브라우저 설정에서 허용하거나 합성 영상을 이용하세요.':e.message;}}}
function demo(){stop();input.width=view.width=384;input.height=view.height=288;view.parentElement.style.aspectRatio='4 / 3';prepare('demo');$('status').textContent='합성 3D 장면 · 같은 영상 추적·자세 추정 경로로 계산합니다.';frameHandle=requestAnimationFrame(loop);}
function renderDemo(){let f=384/(2*Math.tan(65*Math.PI/360)),t=demoFrame++/30,cx=1.5*Math.sin(t*.22),cz=.4*Math.sin(t*.15);ic.fillStyle='#18232d';ic.fillRect(0,0,384,288);for(let [x,y,z,l] of scene){let depth=z-cz,u=f*(x-cx)/depth+192,v=f*y/depth+144,size=Math.max(2,10/depth);if(u<0||u>384||v<0||v>288)continue;ic.fillStyle=`rgb(${l},${l},${l})`;ic.fillRect(u-size,v-size,size*2,size*2);ic.fillStyle='#101820';ic.fillRect(u,v,size,size);}}
function loop(now){if(!running)return;frameHandle=requestAnimationFrame(loop);if(busy||now-lastFrame<33||(mode==='camera'&&(video.readyState<2||video.currentTime===lastMedia)))return;lastFrame=now;if(mode==='demo')renderDemo();else{ic.drawImage(video,0,0,input.width,input.height);lastMedia=video.currentTime;}ctx.drawImage(input,0,0);let data=ic.getImageData(0,0,input.width,input.height),f=input.width/(2*Math.tan((mode==='demo'?65:+$('fov').value)*Math.PI/360));busy=true;worker.postMessage({epoch,pixels:data.data.buffer,width:input.width,height:input.height,focal:f},[data.data.buffer]);}
worker.onmessage=e=>{let d=e.data;if(d.type==='ready'){ready=true;$('camera').disabled=false;$('demo').disabled=false;$('status').textContent='준비됐습니다. 카메라 또는 합성 영상으로 시작하세요.';return;}busy=false;if(!running||d.epoch!==epoch)return;if(d.type==='error'){$('status').textContent='계산 오류 · '+d.message;stop();return;}let now=performance.now();if(lastResult)$('fps').textContent=(1000/(now-lastResult)).toFixed(1);lastResult=now;frameCount++;$('features').textContent=d.tracks.length;$('ms').textContent=d.ms.toFixed(0);$('resolution').textContent=input.width+' × '+input.height+' / WASM';$('status').textContent=d.status+(mode==='demo'?' · 합성 영상':'');ctx.strokeStyle='#8df3c388';ctx.fillStyle='#8df3c3';ctx.lineWidth=1;for(let [x,y,u,v] of d.tracks){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(u,v);ctx.stroke();ctx.fillRect(u-1,v-1,2,2);}if(d.pose){let {R,t,inliers}=d.pose,rt=VOGeometry.tr(R),step=VOGeometry.mv(world,VOGeometry.mv(rt,t).map(x=>-x));position=position.map((x,i)=>x+step[i]);world=VOGeometry.mul(world,rt);path.push(position.slice());if(path.length>2000)path.shift();keyframes++;$('inliers').textContent=inliers.length;drawMap();}window.voDiagnostics={mode,frames:frameCount,keyframes,tracks:d.tracks.length,ms:d.ms,position:position.slice(),pathLength:path.length};};
worker.onerror=e=>{stop();ready=false;$('camera').disabled=$('demo').disabled=true;$('status').textContent='엔진을 불러오지 못했습니다. 페이지를 새로 열어 주세요. '+e.message;};
let imuCount=0,imuStart=0,imuLast=0,imuConnectedAt=0,imuTimer=null;const fmt=v=>Number.isFinite(v)?v.toFixed(2):'—';function onMotion(e){imuCount++;imuLast=performance.now();let a=e.acceleration,r=e.rotationRate,g=e.accelerationIncludingGravity;$('acc').textContent=[a?.x,a?.y,a?.z].map(fmt).join(' / ');$('gyro').textContent=[r?.alpha,r?.beta,r?.gamma].map(fmt).join(' / ');$('gravity').textContent='중력 포함: '+[g?.x,g?.y,g?.z].map(fmt).join(' / ');$('imuState').textContent='수신 중';}
$('imu').onclick=async()=>{try{if(!isSecureContext)throw new Error('HTTPS에서 연결하세요.');if(typeof DeviceMotionEvent==='undefined')throw new Error('이 브라우저는 동작 센서를 제공하지 않습니다.');if(typeof DeviceMotionEvent.requestPermission==='function'){let p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('동작 센서 권한이 거절되었습니다.');}window.removeEventListener('devicemotion',onMotion);window.addEventListener('devicemotion',onMotion);imuCount=0;imuStart=performance.now();imuConnectedAt=imuStart;imuLast=0;$('imu').disabled=true;$('imuState').textContent='센서 신호 대기…';clearInterval(imuTimer);imuTimer=setInterval(()=>{let now=performance.now(),elapsed=(now-imuStart)/1000;$('imuHz').textContent=(imuCount/Math.max(elapsed,.001)).toFixed(1)+' Hz';if(now-(imuLast||imuConnectedAt)>3000){$('imuState').textContent='신호 없음 · 기기·권한 확인';$('imu').disabled=false;$('imuHz').textContent='0 Hz';}imuCount=0;imuStart=now;},1000);}catch(e){$('imuState').textContent=e.message;}};
$('camera').onclick=startCamera;$('demo').onclick=demo;$('stop').onclick=()=>{stop();$('status').textContent='중지했습니다. 카메라와 센서 연결을 해제했습니다.';};$('reset').onclick=reset;$('fov').oninput=()=>{$('fovValue').textContent=$('fov').value+'°';reset();};document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();$('status').textContent='백그라운드로 전환되어 중지했습니다. 다시 시작해 주세요.';}});window.addEventListener('pagehide',stop);drawMap();
