importScripts('geometry.js','vendor/opencv.js');
let api,prev=null,pts=null,anchors=[],age=0,W=0,H=0;
cv.then(c=>{api=c;postMessage({type:'ready'});});
function reset(){if(prev)prev.delete();if(pts)pts.delete();prev=pts=null;anchors=[];age=0;}
function seed(gray){if(pts)pts.delete();pts=new api.Mat();let mask=new api.Mat();try{api.goodFeaturesToTrack(gray,pts,220,.015,9,mask,3,false,.04);}finally{mask.delete();}anchors=Array.from({length:pts.rows},(_,i)=>[pts.data32F[2*i],pts.data32F[2*i+1]]);age=0;}
onmessage=e=>{if(e.data.type==='reset'){reset();return;}if(!api)return;let t=performance.now(),{epoch,pixels,width,height,focal}=e.data;let mats=[];const make=()=>{let m=new api.Mat();mats.push(m);return m;};try{if(width!==W||height!==H){reset();W=width;H=height;}let rgba=api.matFromArray(H,W,api.CV_8UC4,new Uint8Array(pixels));mats.push(rgba);let gray=make();api.cvtColor(rgba,gray,api.COLOR_RGBA2GRAY);let tracks=[],pose=null,status='특징점 준비';
if(prev&&pts&&pts.rows>=16){let next=make(),ok=make(),err=make(),back=make(),bok=make(),berr=make(),size=new api.Size(21,21),crit=new api.TermCriteria(api.TermCriteria_COUNT|api.TermCriteria_EPS,20,.03);api.calcOpticalFlowPyrLK(prev,gray,pts,next,ok,err,size,3,crit);api.calcOpticalFlowPyrLK(gray,prev,next,back,bok,berr,size,3,crit);let cur=[],ref=[];for(let i=0;i<pts.rows;i++){let x=next.data32F[i*2],y=next.data32F[i*2+1];if(ok.data[i]&&bok.data[i]&&err.data32F[i]<35&&Math.hypot(back.data32F[i*2]-pts.data32F[i*2],back.data32F[i*2+1]-pts.data32F[i*2+1])<1&&x>8&&x<W-8&&y>8&&y<H-8){cur.push([x,y]);ref.push(anchors[i]);tracks.push([anchors[i][0],anchors[i][1],x,y]);}}age++;let flow=VOGeometry.med(cur.map((p,i)=>Math.hypot(p[0]-ref[i][0],p[1]-ref[i][1])));status=cur.length<30?'추적 손실 · 다시 시작':flow<4?'이동 대기':'시차 확인 중';if(cur.length>=30&&flow>=4&&age%3===0){let a=ref.map(p=>[(p[0]-W/2)/focal,(p[1]-H/2)/focal]),b=cur.map(p=>[(p[0]-W/2)/focal,(p[1]-H/2)/focal]);pose=VOGeometry.estimate(a,b,focal);if(pose)status='상대 자세 추정';}
if(pose||cur.length<40||age>60){seed(gray);if(!pose&&age>60)status='기준 영상 갱신';}else{pts.delete();pts=api.matFromArray(cur.length,1,api.CV_32FC2,cur.flat());anchors=ref;}}
else seed(gray);if(prev)prev.delete();prev=gray.clone();postMessage({type:'result',epoch,tracks,pose,status,ms:performance.now()-t});}catch(err){reset();postMessage({type:'error',epoch,message:String(err)});}finally{for(let m of mats)m.delete();}};
